import localFont from "next/font/local"
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const Mortend = localFont({
  src: "../fonts/MortendBold.otf"
})

const HeyFont = localFont({
  src: "../fonts/Feeling Passionate Personal Use Only.ttf"
})

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});     

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
